rusterlium/rustler

rustler_codegen/Cargo.toml, rustler_codegen/src/export.rs, rustler_codegen/src/resource.rs
Hello, I'm the developer of `easy-plugin`. I pushed an update today that made some breaking changes, this pull request fixes them in your project. The impact ended up being very small, but I decided to make the pull request anyway. :)
=> bump easy-plugin version

test/test.exs
Couldn't get the tests to run without this...
=> use Rustler.load_nif/2 in RustlerNative test module

src/atom.rs, src/dynamic.rs, src/lib.rs, src/list.rs, src/wrapper/atom.rs, src/wrapper/check.rs, src/wrapper/list.rs, src/wrapper/mod.rs
Add support for term type checking.
=> Dynamic terms

src/atom.rs, src/binary.rs, src/codegen_runtime.rs, src/dynamic.rs, src/ex_struct.rs, src/lib.rs, src/list.rs, src/map.rs, src/resource.rs, src/term.rs, src/tuple.rs, src/types.rs, src/wrapper/atom.rs, src/wrapper/exception.rs, src/wrapper/list.rs, src/wrapper/map.rs, src/wrapper/nif_interface.rs, test/lib/rustler_test.ex, test/src/lib.in.rs, test/src/test_atom.rs, test/test/atom_test.exs
Adds a lot of functions to NifTerm instead of having them be freestanding,
Do not merge yet.
=> Term methods

rustler_codegen/src/map.rs, rustler_codegen/src/resource.rs, rustler_codegen/src/tuple.rs, src/codegen_runtime.rs, src/lib.rs, src/resource.rs, src/schedule.rs, src/term.rs, src/thread.rs, src/types/atom.rs, src/types/binary.rs, src/types/elixir_struct.rs, src/types/list.rs, src/types/map.rs, src/types/mod.rs, src/types/primitive.rs, src/types/string.rs, src/types/tuple.rs, test/src/lib.in.rs, test/src/test_atom.rs, test/src/test_binary.rs, test/src/test_list.rs, test/src/test_map.rs, test/src/test_primitives.rs, test/src/test_resource.rs, test/src/test_thread.rs
see the commit message for more
=> Switch from `&'a NifEnv` to `NifEnv<'a>`

rustler_mix/guides/Basics.md, rustler_mix/mix.exs, rustler_mix/priv/templates/basic/Cargo.toml.exs, rustler_mix/priv/templates/basic/src/lib.in.rs, rustler_mix/priv/templates/basic/src/lib.rs
This change also includes an update to the Basics.md
=> Update rustler.new templates

src/codegen_runtime.rs, src/export.rs, src/resource.rs, src/wrapper/resource.rs, test/src/lib.in.rs, test/src/test_resource.rs
This is kind of a lot of random small changes. It might be easier to review by looking at the commits one by one, rather than the overall diff.
=> Resource tweaks

src/types/mod.rs, test/lib/rustler_test.ex, test/src/lib.rs, test/src/test_primitives.rs, test/test/primitives_test.exs
The flip-side of #94, with tests for decoding and encoding.
=> implement NifDecoder for Option<T> and Result<T,E>

rustler_mix/lib/mix/tasks/compile.rustler.ex
@tridius Does this fix your issue?
=> Attempt at fixing mix compiler on Windows

rustler_mix/lib/mix/tasks/compile.rustler.ex
=> Fix return value for compiler `run` callback on `prod` environment

src/env.rs, src/error.rs, src/lib.rs
@hansihe what do you think about this? I think it cleans things up a bit.
=> Move Env and Error to modules

Cargo.toml, rustler_mix/priv/templates/basic/Cargo.toml.exs, rustler_mix/test/toml_parser_test.exs, tests/Cargo.toml
=> Update lazy_static to 1.0

rustler_mix/lib/rustler/toml_parser.ex, rustler_mix/test/toml_parser_test.exs
=> Fix toml parser

.gitignore, rustler_codegen/src/ex_struct.rs, rustler_tests/src/test_codegen.rs
=> Fix for Github issue #152

rustler_codegen/src/lib.rs
Added a bunch of user documentation to the codegen crate. Will prevent a user from having to troll through the source and test code to figure stuff out.
=> Added documentation on codegen functions.

rustler_mix/lib/mix/tasks/compile.rustler.ex, rustler_mix/lib/rustler/compiler/messages.ex, rustler_mix/lib/rustler/toml_parser.ex
=> Add support for compiling Rust binaries

rustler_mix/lib/rustler.ex
=> Fix load error

rustler/build.rs, rustler_sys/.gitignore, rustler_sys/build.rs, rustler_sys/gen_api.erl, rustler_sys/generate_precompiled.sh, rustler_sys/precompiled/nif_api.4.snippet, rustler_sys/precompiled/nif_api.8.snippet
Should fix #236 and similar issues.
=> Fall back to precompiled API snippet if gen_api.erl fails

rustler_mix/lib/mix/tasks/rustler.new.ex
=> rustler_mix: Mix format

.github/workflows/main.yml
- Fix deprecation warnings from the clippy action
- Fix double CI build for pull-requests
=> Update Github workflow for clippy/rustfmt

rustler/src/types/mod.rs, rustler_tests/lib/rustler_test.ex, rustler_tests/native/rustler_test/src/lib.rs, rustler_tests/native/rustler_test/src/test_map.rs, rustler_tests/test/map_test.exs
=> Implement Encode/Decode for HashMap

rustler_codegen/src/untagged_enum.rs, rustler_tests/lib/rustler_test.ex, rustler_tests/native/rustler_test/src/lib.rs, rustler_tests/native/rustler_test/src/test_codegen.rs, rustler_tests/test/codegen_test.exs
=> Fix generic types for untagged enum codegen

.github/workflows/main.yml
CI should also test Elixir v1.12.
=> ci: Test against v1.12

rustler/src/term.rs, rustler/src/types/local_pid.rs, rustler_tests/lib/rustler_test.ex, rustler_tests/native/rustler_test/src/lib.rs, rustler_tests/native/rustler_test/src/test_term.rs, rustler_tests/test/term_test.exs
As per #189 I have done a simple rebase of this feature. 
It's unclear if more work is required but I'm happy to do it if more needs to be done.
=> implement hashing for term (rebased)

.github/workflows/main.yml, rustler_mix/lib/mix/tasks/rustler.new.ex
Closes https://github.com/rusterlium/rustler/issues/412
=> Fix "mix rustler.new" on Elixir 1.13

rustler_codegen/Cargo.toml, rustler_codegen/src/unit_enum.rs
=> Bump heck to 0.4

rustler/src/dynamic.rs
=> Make TermType derive Eq and PartialEq

CHANGELOG.md, rustler/Cargo.toml, rustler_mix/mix.exs, rustler_mix/mix.lock
This PR prepares a new version of rustler.
Fix #433.
=> Rustler v0.24

rustler_codegen/src/ex_struct.rs, rustler_codegen/src/map.rs, rustler_codegen/src/record.rs, rustler_codegen/src/tuple.rs, rustler_codegen/src/unit_enum.rs, rustler_codegen/src/untagged_enum.rs
=> Fix compilation error of `Result` alias

rustler/src/codegen_runtime.rs, rustler/src/types/atom.rs, rustler/src/wrapper/map.rs, rustler_bigint/src/big_int.rs, rustler_codegen/src/encode_decode_templates.rs, rustler_sys/build.rs
=> Fix clippy

CHANGELOG.md
This PR prepares the release of 0.28.0.
=> Prepare release 0.28.0

.github/workflows/main.yml, rustler_tests/lib/rustler_test.ex, rustler_tests/test/term_test.exs
- Bump rustler_sys patch version
- Add OTP26 to CI
=> Add OTP26 to CI and bump rustler_sys

rustler_mix/lib/rustler/compiler/config.ex
=> Move deprecation warning to correct branch

rustler/src/resource/registration.rs, rustler_codegen/src/lib.rs, rustler_codegen/src/resource_impl.rs, rustler_tests/native/rustler_test/src/test_resource.rs
- **Allow overriding the resource type name**
- **Add resource type name argument to macro**
Fixes #637
=> Fix register resource_impl arg and add name override

rustler_mix/lib/rustler.ex, rustler_mix/lib/rustler/compiler.ex
Reverts rusterlium/rustler#624
=> Revert "Recompile if the NIF library is changed/deleted"
