rustler_mix/lib/rustler/compiler/messages.ex

add `:no_config` message for the cases that users forgot to configure `rustler_crates`

Add :no_config message

---

rustler_codegen/Cargo.toml
rustler_codegen/src/util.rs

The latest version of `easy_plugin` has some breaking changes. I wanted to make sure it still worked with your project, and it does. Here are the changes needed to compile on the latest nightly/syntex.

Update for latest nightly/syntex

---

src/export.rs
src/lib.rs
src/wrapper/nif_interface.rs

add nif dirty func flags

---

src/export.rs
src/schedule.rs

This PR gives more ergnomic use of NIF scheduling flags.
```rust
use rustler::schedule::NifScheduleFlags::*;
rustler_export_nifs! {
"Elixir.MyNifModule",
[("normal_nif", 1, normal_nif),
("dirty_cpu_nif", 1, dirty_cpu_nif, DirtyCpu),
("dirty_io_nif", 1, dirty_io_nif, DirtyIo)],
Some(load)
}
```

Rename scheduling flags

---

src/lib.rs
src/thread.rs
src/wrapper/nif_interface.rs
test/lib/rustler_test.ex
test/src/lib.in.rs
test/src/test_thread.rs
test/test/thread_test.exs

This also adds a public `env.error_tuple(reason)` method, just because it's handy.

`rustler::thread::spawn` for threaded NIFs.

---

rustler_mix/lib/rustler/compiler/rustup.ex
rustler_mix/lib/task_compile.ex
rustler_mix/mix.exs

There was a warning introduced in Elixir 1.4 which complained about
zero-arity function calls without parentheses roughly like the
following:
> ```
> warning: variable "foo" does not exist and is beeing expanded to "foo()", please use parentheses to remove the ambiguity or change the variable name
> ```

Make function calls to zero-arity functions explicit

---

src/thread.rs
test/src/test_thread.rs

This change would allow the user to use thread::spawn with things like thread pools. I think this may be a better solution than OwnedEnv because it enables us to easily implement term transfer to the other env.
cc: @scrogson @jorendorff

make thread::spawn more generic

---

rustler_mix/lib/rustler.ex
test/lib/rustler_test.ex

This change improves NIF loading by implementing the `__using__` macro for the `Rustler` module.
Example:
```ex
defmodule Json do
use Rustler, otp_app: :fast_json
def encode(_), do: :erlang.nif_error(:nif_not_loaded)
def decode(_), do: :erlang.nif_error(:nif_not_loaded)
end
```
I have added a module doc to show the various usage options.

Improve NIF loading with `use Rustler`

---

Cargo.toml
src/env.rs
src/thread.rs
src/types/mod.rs
src/types/pid.rs
src/wrapper/mod.rs
src/wrapper/nif_interface.rs
src/wrapper/pid.rs
test/lib/rustler_test.ex
test/src/lib.in.rs
test/src/test_env.rs
test/test/env_test.exs

The first commit adds our own `NifPid` wrapper type (like `NifTerm` and `NifEnv`) and stops exporting `ErlNifPid`.
The second commit adds an `env.send()` method.

`NifPid` and `env.send(pid, message)`

---

src/lib.rs

While making wrapper module private, the `ErlNifTaskFlags` was also shaded. This PR put it under the sun again.

reexport ErlNifTaskFlags

---

src/wrapper/nif_interface.rs

Changed "self::erlang_nif_sys" to ":: erlang_nif_sys" in various spots in nif_interface.rs because the
latter, not the former, is the correct location of erlang_nif_sys module.  The former doesn't compile; the latter does.

Fixed references to erlang_nif_sys in nif_interface.rs

---

src/types/mod.rs

Implementation for built-in types:
`Option::Some(value)` is_encoded as `value_encoded`
`Option::None` is encoded as `:nil`
`Result::Ok(value)` is encoded as `{:ok, value_encoded}`
`Result::Err(err)` is serialized as `{:error, err_encoded}`

implement NifEncoder for Option<T> and Result<T,E>

---

rustler_codegen/src/ex_struct.rs
rustler_codegen/src/lib.rs
test/lib/rustler_test.ex
test/src/lib.rs
test/src/test_codegen.rs
test/src/test_primitives.rs
test/test/codegen_test.exs

Implements #97: a procedural macro that generates `NifEncode` and `NifDecode` implementations to convert between a Rust struct and an Elixir struct. For example, given the following definition:
```rust
#[derive(NifStruct)]
#[module = "MyStruct"]
pub struct MyStruct {
id: i32,
name: String,
}
```
`MyStruct{id: 123, name: "Bob Jefferson".to_owned()}` encodes as 
`%MyStruct{id: 123, name: "Bob Jefferson"}`.

Encode and decode Elixir structs

---

rustler_mix/lib/mix/tasks/compile.rustler.ex

I was searching the Elixir repo for some tips on making the compile task work with umbrella projects.
It turns out you just have to add the `@recursive true` attribute in the task module. :sweat_smile:
I tested a little bit and it seems that my PR does not break individual projects compilation.

Fix for working with umbrella projects

---

rustler_mix/lib/rustler/toml_parser.ex

Fixes deprecation warning during build:
```
==> rustler
Compiling 2 files (.erl)
Compiling 6 files (.ex)
warning: Kernel.to_char_list/1 is deprecated, use Kernel.to_charlist/1
lib/rustler/toml_parser.ex:7
```

Replace Kernel.to_char_list with Kernel.to_charlist

---

rustler_codegen/Cargo.toml
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/lib.rs
rustler_codegen/src/map.rs
rustler_codegen/src/tuple.rs
rustler_codegen/src/unit_enum.rs
rustler_codegen/src/untagged_enum.rs
test/lib/rustler_test.ex
test/src/lib.rs
test/src/test_codegen.rs
test/src/test_dirty.rs
test/test/codegen_test.exs

Implements two new procedural macros, `NifUnitEnum` and `NifUntaggedEnum`, to generate conversion code between Rust Unit / Untagged NewType enums and Elixir values.
**Example**
Given the following Rust code:
```rust
#[derive(NifUnitEnum)]
enum Enum1 {
FooBar,
Baz,
}
#[derive(NifUntaggedEnum)]
enum Enum2 {
A(u32),
B(String),
C(Enum1),
}
```
`Enum1::FooBar` is encoded as `:foo_bar`
`Enum1::Baz` is encoded as `:baz`.
`Enum2::A(123)` is encoded as `123`
`Enum2::B("Hello".into())` is encoded as `"Hello"`
`Enum2::C(Enum1::Foobar)` is encoded as `:foo_bar`

encode and decode Unit + Untagged NewType Enums

---

rustler_codegen/src/lib.rs
rustler_codegen/src/record.rs
test/lib/rustler_test.ex
test/src/lib.rs
test/src/test_codegen.rs
test/test/codegen_test.exs

This changeset adds functionality to derive a Rust struct from an Erlang [record](http://erlang.org/doc/reference_manual/records.html), which could also be generated by a [macro](https://hexdocs.pm/elixir/Record.html) in Elixir. Its advantage over decoding an Elixir struct is reduced runtime overhead, as no maps are involved and tuple elements can be accessed in constant time. Its advantage over decoding directly from a tuple is that it performs a simple check to verify that the record's tag matches the one described with the `tag` attribute of the rust struct. The code merges pre-existing functionality from `NifStruct` and `NifTuple`.
Consider this example taken from the test case. We can define a record using Elixir:
```elixir
defmodule AddRecord do
import Record
defrecord :record, …
```

Encode and decode records (tagged tuples)

---

rustler_mix/priv/templates/basic/README.md

By using :erlang.nif_error/1, false warnings from Dialyzer are suppressed. This should help
users new to Rustler to avoid useless warnings.

Use :erlang.nif_error/1 in README

---

rustler_mix/lib/rustler.ex

Erlang's erlang:load_nif/2 function expects a string() as its first argument. Although the function accepts  binary string as well, dialyzer complains due to a broken contract:
The call erlang:load_nif(_@1::<<_:64,_:_*8>>,_@2::any()) breaks the
contract (Path,LoadInfo) -> 'ok' | Error when Path :: string(), LoadInfo
:: term(), Error :: {'error',{Reason,Text::string()}}, Reason ::
'load_failed' | 'bad_lib' | 'load' | 'reload' | 'upgrade' | 'old_code'
Note that the spec of `erlang:load_nif/2` is likely underspecified in Erlang itself and should probably be reported.

Fix argument type to load_nif

---

rustler_mix/lib/mix/tasks/compile.rustler.ex

Fix #128. Copying the build library on top of a preexisting build can result in a segfault if a node is currently using the already-built library.

Delete preexisting dynamic library first

---

rustler_codegen/src/record.rs
rustler_tests/src/test_codegen.rs

This is a follow-up to PR #153 and re-uses the fix by @kraythen.

Fix attribute order for NifRecord

---

rustler_mix/guides/Basics.md

By using :erlang.nif_error/1, false warnings from Dialyzer are suppressed. This should help
users new to Rustler to avoid useless warnings.

Use :erlang.nif_error/1 in hex doc

---

rustler_mix/lib/mix/tasks/compile.rustler.ex

When using workspaces, it is important that the target directory of
different NIF crates matches. Otherwise, dependencies will be compiled
multiple times. By allowing to set the target directory, we can ensure
that NIF crates are compiled to the same directory, making cargo
workspaces usable.

Allow setting target directory

---

rustler/src/types/atom.rs
rustler/src/wrapper/atom.rs
rustler/src/wrapper/nif_interface.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/src/lib.rs
rustler_tests/src/test_atom.rs
rustler_tests/test/atom_test.exs

- add `Atom::try_from_bytes` which maps to `binary_to_existing_atom/2`
- test testcases for `Atom::{from_bytes,try_from_bytes}`

add Atom::try_from_bytes

---

.cargo/config

Fixes #151 
```
λ cargo build
Compiling void v1.0.2
Compiling unicode-xid v0.0.4                                                                                                                               
Compiling erlang_nif-sys v0.6.4                                                                                                                            
Compiling quote v0.3.15                                                                                                                                    
Compiling unicode-segmentation v1.2.1                                                                                                                      
Compiling lazy_static v1.0.1 …
```

Configure link args with cargo config

---

rustler_codegen/Cargo.toml
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/lib.rs
rustler_codegen/src/map.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs
rustler_codegen/src/unit_enum.rs
rustler_codegen/src/untagged_enum.rs

This pull request bumps the `quote` and `syn` crates to newer versions. As their respective API changed, changes to `rustler_codegen` were necessary (e.g. moving from `Tokens` to `TokenStream`). To simplify using `TokenStream` together with `quote` (e.g. combining multiple `TokenStream` into a single `quote!`), I added `proc_macro2`.

Bump quote and syn using proc_macro2

---

README.md
rustler/Cargo.toml
rustler/build.rs
rustler/src/types/map.rs
rustler/src/wrapper/map.rs
rustler/src/wrapper/nif_interface.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/src/lib.rs
rustler_tests/src/test_map.rs
rustler_tests/test/map_test.exs

This PR adds support for `enif_make_map_from_arrays`. This requires OTP 21.
Fix #157.

Support enif_make_map_from_arrays

---

rustler_codegen/src/ex_struct.rs
rustler_codegen/src/lib.rs
rustler_codegen/src/map.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs
rustler_codegen/src/unit_enum.rs
rustler_codegen/src/untagged_enum.rs
rustler_tests/src/test_codegen.rs

This commit adds attributes for conditional code generation of encode and
decode. Users can now choose if they want both encode and decode
functions to be derived, or only one of those functions.
For example, for the following struct `A`, only encode is derived:
```rust
struct A<'a> {
my_string: &'a str,
}
```
Additionally, this commit also refactors how the module for Elixir
structs or the tag for Erlang records can be set. In addition to the
format `#[module = "A.B.C"]` or `#[tag = "a"]`, the `rustler` attribute
may also be used:
```rust
struct A<'a> {
my_string: &'a str,
}
```
Fix #180

Add rustler attributes for conditional compilation

---

rustler/build.rs

`dbg!()` was introduced in af7b14c.

Remove debug output

---

rustler/build.rs

The version refers to the NIF version, not the ERTS version.

Rename variable in build.rs

---

rustler/src/types/map.rs
rustler/src/wrapper/map.rs
rustler/src/wrapper/nif_interface.rs

Fixes problem where `enif_make_map_from_arrays` was never being used by `map_from_arrays` because it was behind an invalid `cfg` version.
- Fix cfg to be `nif_version_2_14` instead of `nif_2_14`
- Add missing lifetimes to the keys and values in the type signature

Fix map_from_arrays

---

rustler_mix/lib/rustler/toml_parser.ex
rustler_mix/test/rustler/toml_parser_test.exs

Supports Cargo.toml configurations such as:
```toml
[target.'cfg(windows)'.dependencies]
```
which are matched by the lexer as `{:literal, _}` but fail to parse with a function missing error.
Also updates formatting and fixes a broken unit test. See commits.

Parse literals in TOML keys

---

.travis.yml
erl_nif_sys/gen_api.erl
erl_nif_sys/src/erl_nif_sys_api.rs
rustler/build.rs
rustler_tests/test/resource_test.exs

Add support for OTP-22

---

rustler/Cargo.toml
rustler/src/lib.rs
rustler_mix/priv/templates/basic/Cargo.toml.eex
rustler_mix/priv/templates/basic/README.md
rustler_mix/priv/templates/basic/src/lib.rs
rustler_tests/native/rustler_test/Cargo.toml
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_codegen.rs

This change removes the need for users to depend directly on
`rustler_codegen`.

Re-export codegen derives

---

rustler/src/types/elixir_struct.rs
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/map.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs
rustler_tests/test/codegen_test.exs

Currently if you try to decode a struct that has a field with a type mismatch, all you get back is `Argument error`.
We use Rustler to build large application level NIFs, with structs that have many, often nested, fields. This PR attempts to improve the error message to at least pinpoint which field cannot be decoded. I would love feedback on how I could further improve. 
1. Is there a way to raise an Error that is not `ErlangError`?
2. The error message currently now shows the offending field and the struct `Could not decode field :lhs on %AddStruct{}`, should it also show the value?

Better struct decoding error messages

---

rustler/src/types/map.rs
rustler_tests/test/map_test.exs

Currently on master if you pass a shorter list of values than keys to `Term.map_from_arrays` you will get a segfault (you can reproduce with the new test case before the patch is applied). This adds a check that the sizes are the same and returns BadArg otherwise.

Fix segfault in map_from_arrays.

---

erl_nif_sys/gen_api.erl

Fixes #225 by dropping the respective functions from `gen_api.erl`.

Drop new API functions that are actually macros

---

CHANGELOG.md
rustler/src/types/atom.rs
rustler/src/types/mod.rs
rustler/src/types/primitive.rs
rustler/src/types/truthy.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_codegen.rs
rustler_tests/test/codegen_test.exs

This pull request implements the `Truthy` newtype suggested in https://github.com/rusterlium/rustler/issues/215#issuecomment-496675299. This type allows to distinguish between "real" booleans and truthy values (terms not equal `false` or `nil`). Where a "real" boolean is expected, Rust's `bool` can be used directly. Where a truthy value is expected, the newtype `Truthy` can be used.
See #214 for the original failing test case which is fixed by this pull request.

Introduce a Truthy newtype

---

rustler_mix/priv/templates/basic/src/lib.rs

In the generated template, the module namespace is missing

Fix module namespace

---

rustler/src/resource.rs

Clippy in the latest Rust stable emits the following warning:
```console
error: You checked before that `unwrap()` cannot fail. Instead of checking and unwrapping, it's better to use `if let` or `match`.
--> rustler/src/resource.rs:90:18
|
88 |     if res.is_some() {
|        ------------- the check is happening here
89 |         Some(ResourceType {
90 |             res: res.unwrap(),
|                  ^^^^^^^^^^^^
|
= note: `-D clippy::unnecessary-unwrap` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_unwrap
```
This pull request addresses the warning by changing the codes as [suggested by Clippy](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_unwrap).
**Version Info**
Rust …

Fix a Clippy warning (Clippy 0.0.212 / Rust 1.38.0)

---

rustler_codegen/src/ex_struct.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs

This pull request removes some superfluous `use` statements within `rustler_codegen`.

Remove superfluous use statements from proc-macros

---

rustler/Cargo.toml
rustler_codegen/Cargo.toml
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/lib.rs
rustler_codegen/src/record.rs
rustler_sys/Cargo.toml
rustler_tests/native/rustler_test/Cargo.toml

This pull request started as an attempt to bump dependencies. I bumped syn as well as proc-macro2, which resulted in some code churn. While doing that, I realized that the attribute retrieval for `RustlerAttrs` was very hard to read, and even incorrect for retrieving the `module` and `tag` attribute. I fixed that by refactoring the attribute dispatch to happen as early as possible. With that change, I also removed the code for retrieving the module and tag from `record.rs` and `ex_struct.rs` in favor of the new implementation.
Note that this pull request could also be split into two parts, one for bumping the dependencies and the needed migration, and one for the attribute refactoring.
Let me know if this PR is of help to you and if you need further work to be done.

Bump dependencies and refactor attribute retrieval

---

rustler_sys/build.rs

This change makes it possible to compile `rustler_sys` for 32-bit systems.
I was successfully able to run `cargo build` with a target suited for ARM:
```
λ rustup target add armv7-unknown-linux-gnueabihf
λ sudo apt install gcc-arm-linux-gnueabihf
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
λ cargo build --target=armv7-unknown-linux-gnueabihf
Compiling libc v0.2.51
Compiling cc v1.0.35
Compiling autocfg v0.1.2
Compiling rustc-demangle v0.1.13
Compiling proc-macro2 v0.4.27
Compiling cfg-if v0.1.7
Compiling unicode-xid v0.1.0
Compiling syn v0.15.30
Compiling void v1.0.2
Compiling rustler_sys v2.0.0 (/home/scrogson/github/rusterlium/rustler/rustler_sys)
Compiling unicode-segmentation v1.2.1
Compiling lazy_static v1.3.0
Compiling unreachable v0.1.1
Compiling heck …
```

Support target pointer width.

---

rustler/src/export.rs

I've been noticing that when I don't have `Term` in scope in `lib.rs` I get the following error:
```
error[E0277]: the size for values of type `[rustler::term::Term<'_>]` cannot be known at compilation time
--> src/lib.rs:6:1
|
6  | / rustler::init! {
7  | |     "Elixir.Hyperbeam.Native",
8  | |     [
9  | |         ("start", 1, server::start),
...  |
14 | |     Some(server::load)
15 | | }
| |_^ doesn't have a size known at compile-time
|
= help: the trait `std::marker::Sized` is not implemented for `[rustler::term::Term<'_>]`
= note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
= note: all local variables must have a statically known size
= help: unsized locals are gated as an unstable feature
= note: this …
```

use $crate::Term in `init!` macro

---

rustler_codegen/src/context.rs
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/lib.rs
rustler_codegen/src/map.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs
rustler_codegen/src/unit_enum.rs
rustler_codegen/src/untagged_enum.rs

The proc-macro code generation has a lot of duplicate code over multiple modules. This merge request refactors the modules by pulling common code into the `rustler_codegen::context::Context` struct and its functions. This is in part as a preparation for #241 in order to simplify de-duplicating the `field_atoms`.

Refactor codegen

---

rustler_codegen/src/context.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_codegen.rs
rustler_tests/test/codegen_test.exs

This implements support for NifTuple and NifRecord on newtypes or tuple
structs.
Fix #258

codegen: Support newtype and tuple structs

---

rustler_codegen/src/context.rs
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/map.rs
rustler_codegen/src/record.rs
rustler_codegen/src/unit_enum.rs

This pull request deduplicates generating atoms in codegen by generating a module which can be used by both the encoder and decoder.
Fix #241.

Deduplicate field atoms

---

rustler_mix/README.md

The instructions in the `rustler_mix` readme talk about `:rustler_mix`, but there’s only `:rustler_mix` on hex: https://hexdocs.pm/rustler

Instruct on `:rustler` instead `:rustler_mix`

---

.github/workflows/main.yml
rustler_mix/lib/mix/tasks/rustler.new.ex
rustler_mix/priv/templates/basic/Cargo.toml.eex
rustler_mix/priv/templates/basic/README.md
rustler_mix/priv/templates/basic/src/lib.rs
rustler_mix/test.sh

This pull request adds a shell script to test that the files generated by `rustler_mix` work when used to create a new crate. I fixed some small issues while implementing the script, and extended the mix task to allow specifying the module, name and otp app on the command line.

Test rustler_mix generated files

---

.github/workflows/main.yml
rustler_mix/test.sh

Another fix for #266 (d7552b4). This also adds the event `pull_request` to github actions in order to try to test this PR before it hits master. We can drop this commit when CI succeeded.

rustler_mix: Fix template test on Elixir < 1.9

---

README.md
rustler/Cargo.toml
rustler/src/codegen_runtime.rs
rustler/src/env.rs
rustler/src/export.rs
rustler/src/lib.rs
rustler/src/nif.rs
rustler/src/return.rs
rustler/src/types/atom.rs
rustler_codegen/Cargo.toml
rustler_codegen/src/init.rs
rustler_codegen/src/lib.rs
rustler_codegen/src/nif.rs
rustler_mix/priv/templates/basic/src/lib.rs
rustler_mix/test.sh
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_atom.rs
rustler_tests/native/rustler_test/src/test_binary.rs
rustler_tests/native/rustler_test/src/test_codegen.rs
rustler_tests/native/rustler_test/src/test_dirty.rs
rustler_tests/native/rustler_test/src/test_env.rs
rustler_tests/native/rustler_test/src/test_list.rs
rustler_tests/native/rustler_test/src/test_map.rs
rustler_tests/native/rustler_test/src/test_primitives.rs
rustler_tests/native/rustler_test/src/test_range.rs
rustler_tests/native/rustler_test/src/test_resource.rs
rustler_tests/native/rustler_test/src/test_term.rs
rustler_tests/native/rustler_test/src/test_thread.rs
rustler_tests/test/atom_test.exs
rustler_tests/test/term_test.exs

I've got the new macros all working! :tada:
I'm pretty excited about this, but I'm pretty sure there are some opportunities for some clean up.
~One thing I've noticed is that if you specify any term which is has `decode` called on it, that function needs to return a `Result<T, E>`. It would be nice to avoid this if possible.~
Let me know what you think.

NIF Codegen rework

---

rustler/src/error.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_error.rs
rustler_tests/test/error_test.exs

Hi! I added a variant to return any encoder as an error. I think could help ergonomics and help return more meaningful errors from our native Rustler interfaces to Elixir.
Feedback is appreciated. :)

Added Error::Term for returning `{:error, <term>}`

---

rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_nif_attrs.rs
rustler_tests/test/nif_attrs_test.exs

Test that a NIF can be renamed using the `name` attribute.

Test renaming a NIF

---

rustler_codegen/src/nif.rs

An unknown NIF attribute should result in an error instead of being ignored. Example:
```rust
#[rustler::nif(schedul = "DirtyIo")]
pub fn dirty_io() -> Atom {
let duration = Duration::from_millis(100);
std::thread::sleep(duration);
atoms::ok()
}
```
Resulting error:
```
error: custom attribute panicked
--> rustler_tests/native/rustler_test/src/test_dirty.rs:18:1
|
18 | #[rustler::nif(schedul = "DirtyIo")]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: message: Unknown attribute 'schedul'. Allowed attributes: ["schedule", "name"]
```

Validate NIF attributes

---

rustler_sys/build.rs

Windows long is always 4 bytes wide

---

rustler_mix/mix.exs

Toml is only used when compiling.
Fix #287.

Do not include toml in runtime

---

rustler/src/codegen_runtime.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_binary.rs
rustler_tests/test/binary_test.exs

This implements #286 by allowing a way to return `OwnedBinary` without explicitly converting it into a `Binary`. I also changed the generic signature of `NifReturnable for Result<T, crate::error::Error>` so it works with all `NifReturnable` types.

Make OwnedBinary NifReturnable

---

rustler/src/env.rs

This change fixes a segfault we found today. This was the diff that @evnu posted which does indeed fix the segfault.
I built `OTP-22.2` with `valgrind` and ran it before and after, which can be seen [here].
[here]: https://gist.github.com/scrogson/d4e11b23b946ef9fa2c7e09a4b38709d

Fix Segfault in OwnedEnv::send_and_clear

---

rustler_codegen/src/ex_struct.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs

This reverts commit afda9b886c694366af8460dc5e9940808a7f6670. The `use` statements are needed when a user did not already `use rustler::Encoder`. A  user would have to manually add the `use` statement, which is cumbersome.

Revert "Remove superfluous use statements from proc-macros (#240)"

---

rustler/Cargo.toml
rustler/build.rs

std::process::Command determines the path to an executable using the os-specific PATH variable. As we are only interested in calling the `erl` executable when building, but not where the executable is placed within the file system, we can attempt to call it directly. The dependency was introduced with #178.

Drop dependency on 'which' crate

---

release.sh
rustler_mix/mix.exs

This changes the `release.sh` script to create releases.
* The release commit is tagged
* The `rustler_mix` documentation points to that tag
* If an error occurs during verification by compile, the commit is reverted. This is not done when publishing is already underway!
The PR adds two environment variables for the script to simplify testing:
* `DRYRUN`: Do not publish
* `DONTREVERT`: Do not revert the changes if an error happened or if `DRYRUN` was used

Tag releases and make release script more resilient

---

rustler_codegen/src/context.rs
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/map.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_codegen.rs
rustler_tests/test/codegen_test.exs

This pull request enables using reserved keywords as fields in structs when using the `r#` syntax.
Fix #297

Allow using reserved keywords as field names in codegen

---

CHANGELOG.md
rustler_codegen/src/context.rs
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/map.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs
rustler_tests/native/rustler_test/src/test_codegen.rs

This pull request speeds up compilation by extracting common code from field assignments into helper functions, and by preferring local variables for initial assignment instead of assigning struct fields directly. See #299 for the corresponding issue.
Fix #299.

Speed up generated decoder compilation times

---

rustler/Cargo.toml
rustler/build.rs

This PR removes the build dependency on `lazy_static` from `rustler`.

Remove lazy_static build dependency

---

.github/workflows/main.yml
rustler/src/dynamic.rs

This PR extends the CI pipeline to run the tests on windows as well. I added a specific test for windows, as installing different versions of Elixir and Erlang is cumbersome using chocolatey.

Run github actions on windows-latest

---

.github/workflows/main.yml
rustler_tests/test/env_test.exs
rustler_tests/test/thread_test.exs

This adds Elixir v1.10 to the CI pipeline. It seems that the setup-elixir action does not yet support this version. See [here](https://github.com/actions/setup-elixir/issues/16).

Add Elixir v1.10 to github actions

---

rustler_mix/README.md
rustler_mix/lib/mix/tasks/compile.rustler.ex
rustler_mix/lib/rustler.ex
rustler_mix/lib/rustler/compiler.ex
rustler_mix/lib/rustler/compiler/config.ex
rustler_mix/mix.exs
rustler_mix/mix.lock
rustler_mix/priv/templates/basic/Cargo.toml.eex
rustler_mix/priv/templates/basic/README.md
rustler_mix/test.sh
rustler_tests/lib/binary_example.ex
rustler_tests/mix.exs
rustler_tests/native/rustler_test/Cargo.toml
rustler_tests/native/rustler_test/src/main.rs
rustler_tests/test/binary_example_test.exs

Currently the mix compiler adds additional work for users in order to get started. The changes proposed in this PR aims to make this go away completely and allow users to turn off compilation completely in favor of loading a pre-compiled binary.
**Pros**
* Users no longer need to add the `rustler` compiler in `mix.exs`
* Users no longer need to add the `rustler_crates` option in `mix.exs`
* Crates are automatically compiled when the associated NIF module is compiled.
* Recompilation only happens when one of Rust files or the NIF module are updated (see [`@external_resource`](https://hexdocs.pm/elixir/Module.html#module-external_resource)).
**Cons**
~* Currently, when changes are made to the rust files in the project, `mix compile` does not recompile unless the NIF module has been saved.~ …

Refactor compilation

---

rustler_mix/mix.lock

This PR bumps earmark to v1.4.4. It resolves a warning:
```
warning: duplicate key :inside_code found in struct
(elixir 1.10.3) lib/kernel/utils.ex:119: Kernel.Utils.warn_on_duplicate_struct_key/1
(elixir 1.10.3) lib/kernel/utils.ex:98: Kernel.Utils.defstruct/2
lib/earmark/line.ex:79: (module)
(elixir 1.10.3) src/elixir_compiler.erl:75: :elixir_compiler.dispatch/4
(elixir 1.10.3) src/elixir_compiler.erl:60: :elixir_compiler.compile/3
```

Bump earmark to v1.4.4

---

rustler/src/types/binary.rs

Got removed in PR #239, reported in #315.
I'll port this back to 0.21 if it gets merged.
I'm not sure why I removed those `derive`s, maybe it was a merge error.

Readd Copy and Clone on Binary

---

rustler/src/export.rs
rustler_codegen/src/init.rs

This function is not supposed to get called by anyone but the BEAM, so we can make it private. This also fixes #319 since we don't dereference a pointer in a public "safe" function anymore.

Make the generated nif_init private

---

.github/workflows/main.yml
rustler_codegen/src/context.rs

@hazardfn found that NIF loading sometimes fails, see https://github.com/rusterlium/rustler/issues/324. We should also test against OTP 23.

ci: Test OTP 23

---

rustler/src/types/mod.rs

```
--> rustler/src/types/mod.rs:138:18
|
138 |         let it = MapIterator::new(term).ok_or_else(|| Error::BadArg)?;
|                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: Use `ok_or` instead: `MapIterator::new(term).ok_or(Error::BadArg)`
|
= note: `-D clippy::unnecessary-lazy-evaluations` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_lazy_evaluations
```

Fix clippy lint

---

rustler/src/types/binary.rs

`release` signals to `OwnedBinary`'s `Drop` implementation whether or not call `enif_release_binary()`. The only place that changes `release` from `true` to `false` is in `Binary::from_owned()`. We can therefore remove the release flag altogether by simply preventing `drop()` in `Binary::from_owned()`.

Remove OwnedBinary's release flag

---

rustler_codegen/src/ex_struct.rs
rustler_codegen/src/map.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs
rustler_codegen/src/unit_enum.rs
rustler_codegen/src/untagged_enum.rs

This PR uses spans to add source-of-error messages when a rustler derive macro fails.
```rust
use rustler::{NifMap, NifRecord, NifStruct, NifTuple, NifUnitEnum, NifUntaggedEnum};
/// This struct does not implement Encoder/Decoder
pub struct C(i32);
#[derive(NifStruct)]
#[module = "AddStruct"]
struct AddStruct {
lhs: i32,
rhs: C,
}
#[derive(NifMap)]
struct AddMap {
lhs: i32,
rhs: C,
}
#[derive(NifRecord)]
#[tag = "record"]
struct AddRecord {
lhs: i32,
rhs: C,
}
#[derive(NifTuple)]
struct AddTuple {
lhs: i32,
rhs: C,
}
#[derive(NifUnitEnum)]
enum UnitEnum {
FooBar,
Baz(u8),
}
#[derive(NifUntaggedEnum)]
enum UntaggedEnum {
Foo(u32),
Bar(String),
Baz(i32,i32),
}
```
```
error: NifUnitEnum can only be used with enums containing unit variants.
--> src/nifmap.rs:34:5
|
34 |     Baz(u8),
| …
```

Improve error messages on failure to derive

---

rustler/src/types/binary.rs
rustler/src/types/mod.rs

For my colleagues and I, one of the hardest parts of coming up to speed with Rustler has been dealing with binaries. Even those of us with years of Rust experience were confused by the difference between `Binary` and `OwnedBinary`, despite the fact that `Owned` should say it all.  I've tried my best to capture my confusion before I'm too familiar with codebase. 
Included in this PR:
- add module-level for the binary module, thus I had to remove the `doc_hidden` tag
- When adding a `# Panics` section for `OwnedBinary::from_unowned`, I noticed that it could be simplified to the point that it's obvious that it will not panic (it calls `copy_from_slice` internally, which can panic, but won't since lengths will be checked before that call)
- documents all binary api functions, even if …

Improve binary documentation

---

.github/workflows/main.yml
rustler_mix/mix.exs

In elixir 1.11 I'm getting the following compile warnings during rustler compilation.
```
==> rustler
Compiling 5 files (.ex)
warning: EEx.eval_string/3 defined in application :eex is used by the current application but the current application does not directly depend on :eex. To fix this, you must
do one of:
1. If :eex is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs
2. If :eex is a dependency, make sure it is listed under "def deps" in your mix.exs
3. In case you don't want to add a requirement to :eex, you may optionally skip this warning by adding [xref: [exclude: EEx]] to your "def project" in mix.exs
lib/mix/tasks/rustler.new.ex:79: Mix.Tasks.Rustler.New.copy_from/3
warning: Toml.decode!/1 defined in application :toml …
```

Fix warnings

---

rustler/src/env.rs
rustler/src/resource.rs
rustler/src/types/atom.rs
rustler/src/types/tuple.rs
rustler_codegen/src/nif.rs
rustler_sys/src/rustler_sys_api.rs

This PR fixes the following clippy lints:
* `unusual_byte_groupings`
* `needless_lifetimes`
* `unnecessary_cast`

Fix clippy lints

---

.github/workflows/main.yml

Clippy regularly fails on new pull requests due to changes in nightly. We only find out about that if somebody actually publishes a PR. As people publishing PRs are unlikely to run nightly, we can't really assume that they can or will take care of such lints. Instead, we should simply change the toolchain to nightly.

ci: Use stable toolchain for clippy and format

---

.cargo/config

The previous target works on Intel based Macs but was causing an issue on the new Apple Silicon based Macs.

Update rust linker flags to apply to macOS

---

.github/workflows/main.yml

Github [no longer allows](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) using stdout to extend the PATH variable:
This pull request migrates to the new [format](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path).

ci: Fix adding erlang to PATH in windows runnner

---

.github/workflows/main.yml

Run the CI jobs periodically to ensure that we keep up with nightly.
This is an alternative to https://github.com/rusterlium/rustler/pull/343.

ci: Run jobs on wednesday night

---

.github/workflows/main.yml

From [here](https://github.com/actions/setup-elixir/blob/main/README.md):
> Please note: This repository is currently unmaintained by a team of developers at GitHub. It is now maintained by the Erlang Ecosystem Foundation at erlef/setup-elixir.

ci: Switch from actions/setup-elixir to erlef/setup-elixir

---

rustler/src/wrapper.rs
rustler_sys/src/rustler_sys_api.rs

This disables `clippy::upper-case-acronyms` for `rustler_sys_api.rs` and `wrapper.rs`:
```
error: name `ERL_NIF_UINT` contains a capitalized acronym
--> rustler_sys/src/rustler_sys_api.rs:17:10
|
17 | pub type ERL_NIF_UINT = size_t;
|          ^^^^^^^^^^^^ help: consider making the acronym lowercase, except the initial letter: `Erl_Nif_Uint`
|
= note: `-D clippy::upper-case-acronyms` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms
```

Disable lint for rustler_sys_api

---

rustler/src/types/primitive.rs

Decoding `f32` is made using `enif_get_double`, which obviously consumes values bigger than `f32:MAX`.
Then, `ret as f32` not limiting the value by it's max, either turn it to be `f32:INFINITY`. This leads to confusions and even nif panics.

Fix f32 type conversion to be safe

---

rustler_codegen/src/lib.rs

Just a trivial change. The second, duplicated `add` should actually be a `sub`.

Duplicate "add" function in the docs.

---

rustler_mix/lib/rustler/compiler.ex
rustler_mix/lib/rustler/compiler/config.ex

This fixes f01719c: We accidentally removed a workaround for mix, which copied the libraries to the target directory in `_build`. d053522f originally introduced a workaround, copying `symlink_or_copy`. Here, we call into a public function of `Mix.Project` instead (which might be more future proof).
Fix #326

Add workaround for missing lib

---

CHANGELOG.md

We warn w.r.t. deprecation in `compiler.rustler.ex` and refer to the CHANGELOG, but the CHANGELOG did not yet contain an entry discussing the deprecation.

Add deprecation note to CHANGELOG

---

CHANGELOG.md
UPGRADE.md

This adds a new `UPGRADE.md` file, which can be used to explain how to migrate to new versions.

Add UPGRADE.md for v0.22

---

rustler/src/types/binary.rs
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/map.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs
rustler_codegen/src/unit_enum.rs
rustler_codegen/src/untagged_enum.rs
rustler_sys/src/initmacro.rs

Fixes a few small clippy lints:
1. Trailing semicolon in macro
2. Needless borrowing

Fix clippy

---

rustler_mix/lib/rustler.ex
rustler_mix/lib/rustler/compiler.ex

This is useful if you want to use e.g. `{:system, "+nightly"}`

Allow specifying a channel for the system rustc

---

rustler/src/lib.rs

Hey folks! 
Was checking this out and I noticed that the URL in `lib.rs` is pointing to a dead link. I _think_ it's related to #270 as it looks like this is when the `mix` documentation was updated. I compared the docs and it looks like the base Rustler module docs cover pretty much everything there. Happy to update this PR if I'm mistaken though.
Thanks for making the project 😄

Point to HexDocs base URL for Rustler in lib.rs

---

CHANGELOG.md
rustler/src/types/atom.rs
rustler/src/types/map.rs
rustler_tests/test/term_test.exs

This fixes #392 by requiring that the `:step` field in `Range` is optional. If it is set, it must be 1 (as we cannot represent another value with Rust's `RangeInclusive`).

Require step for range

---

rustler_sys/build.rs

The target OS selection is not actually being used but is stopping rustler from being used on another very unixy system

Add FreeBSD support

---

rustler/src/types/binary.rs

I have a concrete use-case for this PR: using an `OwnedBinary` as the [key] in caches/maps. I'm currently forced to wrap the binary in a clumsy wrapper struct.
For completeness sake, this PR implements Hash, PartialEq, and Eq for Binary in addition to implementing PartialEq between Binary ⟷ OwnedBinary.
[key]: https://github.com/helium/e2qc/pull/1/files#diff-28b0ccc836e6e883168b88ebb6f39508969ece5516e5f81458abd33592b12430R195-R221

Implement Hash and [Partial]Eq for binary types

---

.github/workflows/main.yml
README.md
rustler_mix/mix.exs
rustler_mix/test.sh
rustler_tests/mix.exs
rustler_tests/test/binary_example_test.exs

The idea is to restrict the versions we support to be the latest 3
versions of Elixir and OTP.
So right now we support Elixir ~> 1.11 and OTP ~> 22.

Change supported Elixir and OTP versions

---

rustler/src/lib.rs
rustler/src/types/atom.rs
rustler/src/wrapper/term.rs
rustler_codegen/src/context.rs
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/lib.rs
rustler_codegen/src/map.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tuple.rs
rustler_codegen/src/unit_enum.rs
rustler_codegen/src/untagged_enum.rs
rustler_sys/src/initmacro.rs
rustler_sys/src/lib.rs
rustler_sys/tests/struct_size.rs

This PR removes `extern crate XYZ` where unnecessary. See the [edition guide](https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html) for edition 2018.

Remove superfluous 'extern crate'

---

rustler_mix/mix.exs

Hello there 👋🏼 
This PR changes the required version of the `jason` dependency for `rustler_mix`. Translating the effect into more readable terms, it aims to do this:
```
mix.exs  effective range
Old:  ~> 1.2   1.2.0 <= x < 2.0.0
New:  ~> 1.0   1.0.0 <= x < 2.0.0
```
Reading through the [`jason` changelog](https://github.com/michalmuskala/jason/blob/master/CHANGELOG.md), it does not appear that this library makes use of any changes that were made between `1.0` and `1.2`. The locked version of `jason` used during development of this library (`1.2.2`) will remain the same.
**Why?** This relaxed version requirement will make it less likely that users of rustler will need to override the version of `jason` used in their project. Occasionally another dependency will lock to a particular …

Relax Jason version requirement to ~> 1.0

---

rustler_mix/lib/rustler/compiler.ex

Hi, this PR aims to fix a small issue when `rustler` is used in a cross-compile environment, i.e., user sets the `target` option to a target triple that is different from the host. 
When cross-compiling from macOS to Linux, `make_file_names/2` will generate filenames based on the `:os.type/0`, which is the settings for the host.
This PR adds `get_target_os_type/1` to fetch the correct os type based on `target` for `make_file_names/2`. If `target` is not a string, i.e., user didn't set this option, then it fallbacks to use `:os.type/0`.
The target list is generated based on `rustc --print target-list`.
```
$ rustc --version
rustc 1.56.1 (59eed8a2a 2021-11-01)
```
Signed-off-by: Cocoa <r.xu.1@research.gla.ac.uk>

file extensions should be set based on the compile target

---

rustler/src/types/binary.rs
rustler/src/wrapper/binary.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_binary.rs
rustler_tests/test/binary_test.exs

It seems like this can improve performance a bit if you're creating a lot of small binaries

add `NewBinary` (`enif_make_new_binary`)

---

rustler/src/lib.rs
rustler/src/types/mod.rs

Thank you for releasing 0.24.0
I tested it and it works great.
This pr just imports `NewBinary` into lib, so `NewBinary` can be imported as `use rustler::NewBinary` instead of `use rustler::types::binary::NewBinary`

import NewBinary in lib

---

rustler/src/types/map.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_map.rs
rustler_tests/test/map_test.exs

This function creates a new map based on a vector of tuples of terms.
It's an alternative to `Term::map_from_arrays`, but it can assert the
shape of pairs in compile time.

Add `Term::map_from_pairs`

---

rustler_mix/lib/rustler/compiler.ex
rustler_mix/lib/rustler/compiler/config.ex

This PR adds a mechanism to search through `.cargo/config` files up from the crate to the workspace root in order to find target configuration for macos. If any such configuration is found, we assume that it contains the linker arguments required to make rustler work on macos.
Fix #235.

Abort compilation on macos if linker arguments are missing

---

.github/workflows/main.yml

Add a CI runner for macOS. On macos, we need to run `rustc` separately for each target in the `Cargo.toml`. The reason is that we currently pass extra linker arguments to `rustc`. This is not possible if multiple targets need to be build.

ci: Add macos runner

---

rustler_codegen/src/context.rs

Those warnings are present when deriving from `NifStruct`.
The convention says that we can't mix
"SCREAMING_SNAKE_CASE_with_snake_case".
https://doc.rust-lang.org/1.0.0/style/style/naming/README.html

Fix snake case warnings for rust analyzer

---

rustler_codegen/src/lib.rs

This clarifies the usage of the `Nif*` derive macros a bit, and removes a few small errors.

Improve documentation of derive macros

---

rustler_codegen/src/lib.rs

Closes https://github.com/rusterlium/rustler/issues/111

Document the usage of `schedule` flag for `nif` macro

---

rustler/src/types/elixir_struct.rs
rustler/src/types/map.rs
rustler/src/types/mod.rs
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/map.rs
rustler_codegen/src/tagged_enum.rs

resolves #451
Change map's helper functions arguments from `Term` into `impl Encoder`.

Change map helper functions' arguments

---

rustler/src/env.rs
rustler/src/types/local_pid.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_env.rs
rustler_tests/test/env_test.exs

I had the requirement to use `whereis_pid` in my code.
However, until now, `enif_whereis_pid` was exposed by `rustler_sys` but not wrapped by `rustler`; there was no way to build a new LocalPid from the returned ErlNifPid (without transmuting).
This PR adds a safe wrapper around it.
Please let me know what you think about the signature and the implementation.

Adds Env.whereis_pid

---

rustler_codegen/src/ex_struct.rs
rustler_codegen/src/map.rs
rustler_codegen/src/tagged_enum.rs

In #453 , I missed some codegen logic that moves certain terms. Originally, they were encoded and passed into the `map_put` or `map_get` function so the move operation occurs, but currently, they are just passed so the move occurs. So I fixed them to pass them as references.
Sorry for making errors!

Fix moving out terms

---

rustler_bigint/Cargo.toml
rustler_bigint/README.md

This PR adds a `README.md` and relevant information in `Cargo.toml` to `rustler_bigint`. With that, we should be able to release the crate soon-ish as a v0.1. @thomas9911  please take a look if I missed something, or maybe if we should add additional information to the README.

Prepare rustler_bigint release

---

rustler_codegen/src/record.rs
rustler_codegen/src/tagged_enum.rs
rustler_codegen/src/tuple.rs
rustler_codegen/src/unit_enum.rs
rustler_codegen/src/untagged_enum.rs
rustler_tests/native/rustler_test/src/test_codegen.rs

Since `encode` and `decode` are very common names, if any traits have those names that exist, the compiler complains about its ambiguity.

Disambiguate `encode` and `decode`

---

rustler_codegen/src/tagged_enum.rs
rustler_tests/native/rustler_test/src/test_codegen.rs
rustler_tests/test/codegen_test.exs

1. Support multiple units with same field names
2. Move atom / tuple decode outside the type check if, to remove duplicate decode calls
Enum with 22 cases:
before:
tagged_enum_decode          1.56 M      642.48 ns  ±1292.75%         634 ns         675 ns
after:
tagged_enum_decode          3.17 M      314.98 ns  ±2092.02%         311 ns         343 ns
(~300ns is also the tagged_enum_encode latency on my machine)

Tagged enum usability & performance improvements

---

Cargo.toml
rustler/src/types/binary.rs
rustler/src/types/list.rs
rustler/src/wrapper/binary.rs
rustler_bigint/src/big_int.rs
rustler_codegen/src/context.rs
rustler_codegen/src/encode_decode_templates.rs
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/lib.rs
rustler_codegen/src/map.rs
rustler_codegen/src/record.rs
rustler_codegen/src/tagged_enum.rs
rustler_codegen/src/tuple.rs
rustler_codegen/src/unit_enum.rs
rustler_codegen/src/untagged_enum.rs
rustler_sys/build.rs
rustler_tests/native/rustler_compile_tests/Cargo.toml
rustler_tests/native/rustler_compile_tests/src/lib.rs

This PR builds on the previous work of @turion (https://github.com/rusterlium/rustler/pull/430), 
@SeokminHong (https://github.com/rusterlium/rustler/pull/430#issuecomment-1175816881) and @neosimsim (https://github.com/rusterlium/rustler/pull/471), so kudos to them, this PR only attempts to complete their prior work.
Handling lifetimes for encoders within `rustler_codegen` is obvious: we can directly use `split_for_impl()` from `syn` to split the generics in a way which allows us to use them for a generated `impl`. For decoders, handling lifetimes is more involved. First of all, we need to ensure that the special lifetime of the decoder (named `'__rustler_decode_lifetime` in the generated code) outlives the lifetimes of the type to which we want to decode. The reason for this is that …

Fix lifetime handling in rustler_codegen

---

.github/workflows/main.yml

- Use `setup-beam` to run CI on Windows
- Use a single entry for Clippy on all OSs (is this really required?)
As soon as https://github.com/erlef/setup-beam/issues/54 lands, we can drop the separate `test_macos`  step as well.

Simplify and fix CI

---

rustler/src/types/binary.rs

Make `OwnedBinary` `Sync`, fixes #469.

Make OwnedBinary Sync

---

rustler/src/wrapper/binary.rs
rustler/src/wrapper/resource.rs

I have decided to use Rustler convention (subbinary) instead of OTP one (sub_binary).

Expose wrapper::binary::make_subbinary

---

rustler_codegen/src/lib.rs

`Some(load)` has been replaced with `load = load`.
Also add a stub for showing how `load` should look like.

rustler_codegen: Fix stale doc example for init

---

.github/workflows/main.yml
rustler_tests/mix.exs
rustler_tests/native/rustler_test/Cargo.toml
rustler_tests/native/rustler_test/src/test_binary.rs
rustler_tests/native/rustler_test/src/test_list.rs
rustler_tests/native/rustler_test/src/test_thread.rs
rustler_tests/test/binary_example_test.exs
rustler_tests/test/binary_test.exs
rustler_tests/test/list_test.exs
rustler_tests/test/thread_test.exs

It removes Elixir 1.11 that is not supported anymore.
It updates the version of Actions in the workflow, and also simplifies by merging parts that are common and can work together.

Simplify CI workflow and update versions

---

rustler_codegen/Cargo.toml
rustler_codegen/src/lib.rs
rustler_codegen/src/nif.rs
rustler_codegen/tests/test.rs
rustler_codegen/tests/ui/nif-macro-unrecognized-attribute.rs
rustler_codegen/tests/ui/nif-macro-unrecognized-attribute.stderr
rustler_codegen/tests/ui/nif-macro-wrong-schedule-attribute-value.rs
rustler_codegen/tests/ui/nif-macro-wrong-schedule-attribute-value.stderr

The idea is to provide more contextual messages when an invalid "schedule" option is used.
This also includes a new dev dependency - [trybuild](https://github.com/dtolnay/trybuild) - that helps with the testing of compile error messages.

Improve nif macro error messages for invalid attributes

---

rustler_codegen/src/context.rs

Since our [MSRV is now Rust 1.56.1](https://github.com/rusterlium/rustler/commit/662d4a31bc7ce5f314ed2237b78dc9df969bc07e), we can fix this clippy issue.

Fix clippy issue in the codegen

---

rustler_tests/native/rustler_test/src/test_tuple.rs

To ensure that MSRV of 1.56.1 still holds, replace the captured identifier in format strings. Capturing identifierts for format strings was introduced with Rust 1.58.0.

Use non-captured identifier in format string

---

rustler_sys/build.rs
rustler_sys/src/rustler_sys_api.rs

Makes `rustler_sys` forward compatible by falling back to the highest available version as long as the NIF major version matches.

Make rustler_sys forward compatible

---

CHANGELOG.md
README.md
UPGRADE.md
build_common.rs
rustler/Cargo.toml
rustler/build.rs
rustler/build_common.rs
rustler_mix/lib/rustler/compiler.ex
rustler_sys/Cargo.toml
rustler_sys/build.rs
rustler_sys/build_common.rs
rustler_sys/src/rustler_sys_api.rs

- Make rustler_sys forward compatible
- Use Cargo features to define the minimal required NIF version
- Stop using RUSTLER_NIF_VERSION in rustler_mix
Another side-effect of this change is that I have completely removed the Erlang call from the build process now as we do not attempt to auto-discover the highest available NIF version anymore. Instead, we compile by default for NIF 2.14, if anything higher is required, it has to be given explicitly as either `RUSTLER_NIF_VERSION` or by defining the respective feature.
I would suggest that we eventually (with rustler-0.29, rustler-sys-2.3.0) retire `RUSTLER_NIF_VERSION` in favour of users defining their `rustler` (or `rustler-sys`) dependency with the minimal required NIF version. This has also the huge advantage of being able to handle …

Use features for minimal NIF version

---

rustler/Cargo.toml
rustler_sys/Cargo.toml
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/Cargo.toml

- Activate matching version feature on the test projects
- Raise default NIF version to 2.15

Apply current NIF version for tests and raise default

---

CHANGELOG.md
rustler/src/lib.rs
rustler/src/types/atom.rs
rustler/src/types/erlang_option.rs
rustler/src/types/mod.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_primitives.rs
rustler_tests/test/primitives_test.exs

This PR fixes #500 by adding a Rust type`ErlOption<T>` to the Rustler crate.
`ErlOption<T>` is a wrapper around `Option<T>`. It implements Rustler's `Encoder` and `Decoder`, and serializes `None` into `undefined` atom instead of `nil`. The `undefined` atom is commonly used in Erlang libraries to express the absence of a value.
For convenience, `ErlOption<T>` implements some traits from `std`, so that it will be easy to get a reference of enclosing `Option<T>` or convert from/to `Option<T>`. Here are the examples from its doc:
```rust
use rustler::ErlOption;
// Create new `ErlOption<i32>` values via convenient functions.
let _ = ErlOption::some(1); // Wraps `Some(1)`.
let _ = ErlOption::<i32>::none();
// Convert Option<i32> values to ErlOption<i32> values.
let _ = ErlOption::from(Some(2)); …
```

rustler: add a Rust type `ErlOption<T>`

---

rustler_mix/lib/rustler/compiler/config.ex

Elixir 1.15 handles external resources differently:
https://github.com/elixir-lang/elixir/blob/v1.15.0/CHANGELOG.md#mix
`[mix compile] Track digests of @external_resources`
It will try to read the file content and compute a digest to know if the file should be recompiled. https://github.com/elixir-lang/elixir/blob/96996cef7dbdbb5daa8c8009d1e51582d4c4023e/lib/mix/lib/mix/compilers/elixir.ex#L445C1-L445C1
Because rustler includes directories in the `@external_resources` module attribute, trying to recompile after a first compilation will fail with this error:
```
** (File.Error) could not read file "native/name_of_project/src": illegal operation on a directory
(elixir 1.15.0) lib/file.ex:358: File.read!/1
(mix 1.15.0) lib/mix/compilers/elixir.ex:441: Mix.Compilers.Elixir.digest_file!/1
(mix …
```

Exclude directories from external resources to be compatible with Elixir 1.15

---

rustler/src/types/map.rs
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/map.rs
rustler_codegen/src/tagged_enum.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_codegen.rs
rustler_tests/test/codegen_test.exs

Hi :wave:,
On rustler 0.28.0, I get an error in the generated code from enums like this:
```rust
#[derive(NifTaggedEnum)]
enum TaggedEnum {
Numbers { unit: Option<String>, values: Vec<f64> }
}
/*
error[E0308]: mismatched types
--> src/types.rs:85:29
|
85 |                     &[unit, values],
|                             ^^^^^^ expected `&Option<String>`, found `&Vec<f64>`
|
= note: expected reference `&std::option::Option<std::string::String>`
found reference `&Vec<f64>`
*/
```
The slice was being passed to `map_from_arrays`. I looked at NifMap's equivalent `gen_named_encoder` and copied the `map_put` strategy, which worked.
If performance is a concern, I think a set of `map_from(env, k1, v1, ...)` functions for small map sizes could accomplish the same thing but still use …

Fix NifTaggedEnum derived Encoder impl for named-field variants

---

rustler_sys/build.rs

By bumping `rustler` to `0.29.0` in a project using `rustler_precompiled`, I realized that the cross-compilation of some targets fails.
For instance,  when compiling rustler with `cargo build --target=arm-unknown-linux-gnueabihf`, the ulong_size is not picked up correctly.
This is because the build.rs is compiled by the host prior to being executed, so the `cfg!` macro refers to the host configuration.
This PR reverts the usage of the `cfg!` macro in favor of the `CARGO_*` env variables.

Remove cfg! directives in build.rs causing cross-compilation to fail

---

CHANGELOG.md
UPGRADE.md
rustler_mix/lib/rustler.ex
rustler_mix/lib/rustler/compiler.ex
rustler_mix/lib/rustler/compiler/config.ex
rustler_mix/lib/rustler/compiler/messages.ex

We also deprecate rustler_crates since that cannot be as efficiently tracked by the Elixir compiler.

Use compile_env for compile-time configuration

---

rustler_mix/lib/rustler.ex
rustler_mix/lib/rustler/compiler.ex
rustler_mix/lib/rustler/compiler/config.ex

This PR removes this warning:
```
warning: variable "module" is unused (if the variable is not meant to be used, prefix it with an underscore)
lib/rustler/compiler/config.ex:35
```

Remove superfluous `module` argument

---

CHANGELOG.md
prepare_release.sh
rustler_benchmarks/mix.exs
rustler_mix/README.md
rustler_mix/lib/rustler.ex
rustler_mix/test.sh

As noted by @hauleth in #516, the rustler dependency is only required at compile time. This PR makes that possible by expanding `Rustler.construct_load_data/2` into the target module. The PR changes the documentation (and a test of the toolchain) to instruct that `runtime: false` can be used with rustler as a dependency.
Fix #516

Document to use runtime: false for rustler dependency

---

CHANGELOG.md
UPGRADE.md
rustler/src/env.rs
rustler/src/thread.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_env.rs
rustler_tests/test/env_test.exs

`Env::send()` and `OwnedEnv::send_and_clear()` should ideally not elide the return value of [`enif_send`](https://www.erlang.org/doc/man/erl_nif#enif_send).
Included are several variants, all of which provide exactly the same information, given the current NIF API.
My take is that the preferred solution would be to pick one and resignature `send()`, but we could also keep some/all of the variants provided instead.
In all cases, resignature would not a breaking API change, but will generate warnings for the `_result` variants. The `_i32` and `_bool` variants are less idiomatic, but do not suffer from this issue. Nonetheless, my thinking is that an unhandled `Result` warning is ideal in this case, as it makes users aware of the fact that they are currently discarding information without …

feat: add result-returning `send` variants to `Env` and `OwnedEnv`

---

rustler_mix/lib/rustler.ex

This expands load data at compile time, thereby resolving a dialyzer warning. Fix #569 .

Expand load data at compile time

---

rustler_codegen/src/context.rs

While hacking on the codebase we noticed that the error messages when creating an incorrect `tag` or `module` are wrong.

Fix error messages

---

rustler_codegen/src/context.rs
rustler_codegen/src/encode_decode_templates.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_codegen.rs
rustler_tests/test/codegen_test.exs

Closes #424. Allows generic type parameters in the derive macros:
```rust
#[derive(NifStruct)]
#[module = "GenericStruct"]
pub struct GenericStruct<T> {
t: T
}
```

Add support for generic types

---

rustler_sys/src/initmacro.rs

Whether c_char is i8 or u8 is platform-dependent
(https://doc.rust-lang.org/std/ffi/type.c_char.html), this is the only place
where it is relevant so far, though. We could adjust the `rustler` struct and
type mappings as well.

Fix rustler_sys tests on 64bit ARM

---

UPGRADE.md
rustler/src/dynamic.rs
rustler/src/term.rs
rustler_sys/build.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_term.rs
rustler_tests/test/term_test.exs

It was not returning the correct type for integers, probably due to a "garbage" arriving because of the wrong type.
This affects the latest v0.30.

Fix Term's "get_type()" implementation

---

rustler/Cargo.toml
rustler/src/codegen_runtime.rs
rustler/src/export.rs
rustler/src/nif.rs
rustler/src/wrapper.rs
rustler/src/wrapper/atom.rs
rustler/src/wrapper/resource.rs
rustler_codegen/src/init.rs
rustler_codegen/src/nif.rs
rustler_sys/Cargo.toml
rustler_sys/build.rs
rustler_sys/src/rustler_sys_api.rs

Probably because Rust always expresses strings as `[u8]`, all `const char*` parameters in the NIF API were translated as `u8` or `uchar`. The correct type for these is `std::ffi::c_char` which is particularly relevant on systems that use a signed `char` type by default (see #584).

Fix type usage to use the real C types wherever applicable

---

CHANGELOG.md
rustler_codegen/src/nif.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/test_nif_attrs.rs
rustler_tests/test/nif_attrs_test.exs

Allow arbitrary ASCII strings as NIF names. Follow-up of #505.

Allow arbitrary function names

---

CHANGELOG.md
rustler/src/types/local_pid.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_env.rs
rustler_tests/test/env_test.exs

Add `Env::is_process_alive` and `LocalPid::is_alive`

---

CHANGELOG.md
rustler/src/types/i128.rs
rustler/src/types/mod.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_primitives.rs
rustler_tests/test/primitives_test.exs

Implement Decoder/Encoder support for i/u128

---

rustler_benchmarks/lib/benchmark.ex
rustler_benchmarks/lib/benchmark/nif_various.ex
rustler_benchmarks/native/benchmark/src/lib.rs
rustler_benchmarks/native/benchmark/src/nif_various.rs

Benchmarks used to verify https://github.com/rusterlium/rustler/pull/482 . At that time there was no benchmarks setup in rustler yet so I didn't include them in the PR. 
As there is now, this might be of use for others or CI/CD integration.

Add additional benchmarks

---

rustler/src/types/mod.rs
rustler/src/types/path.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_path.rs

Implement support for conversions of paths

---

rustler_mix/lib/rustler/compiler/config.ex

Fix a bug when adding a path dependency to a rustler Cargo.toml that gives this cryptic error:
```
== Compilation error in file lib/multiplayer_backend/project_mutator.ex ==
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
(elixir 1.16.1) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir 1.16.1) lib/enum.ex:166: Enumerable.reduce/3
(elixir 1.16.1) lib/enum.ex:4399: Enum.filter/2
(rustler 0.32.1) lib/rustler/compiler/config.ex:130: Rustler.Compiler.Config.gather_local_crates/4
(rustler 0.32.1) lib/rustler/compiler/config.ex:108: Rustler.Compiler.Config.external_resources/3
(rustler 0.32.1) lib/rustler/compiler/config.ex:79: Rustler.Compiler.Config.build/1
(rustler 0.32.1) lib/rustler/compiler.ex:8: Rustler.Compiler.compile_crate/3 …
```

Add support for path dependencies

---

CHANGELOG.md
UPGRADE.md
rustler/Cargo.toml
rustler/src/lib.rs

I see no need to support this right now and from experience, it's enabled pretty much everywhere anyhow. If people ask for it, we can look into providing nicer non-derive interfaces.

Unconditionally enable `derive`

---

rustler_mix/lib/rustler.ex
rustler_mix/lib/rustler/compiler.ex

Recompile if the NIF library is changed/deleted

---

CHANGELOG.md
UPGRADE.md
rustler/src/codegen_runtime.rs
rustler/src/lib.rs
rustler/src/resource/mod.rs
rustler/src/resource/registration.rs
rustler_codegen/src/init.rs
rustler_codegen/src/lib.rs
rustler_codegen/src/resource_impl.rs
rustler_tests/native/rustler_test/src/test_resource.rs

Add automatic resource registration and a resource_impl attribute macro

Resource attribute macro

---

CHANGELOG.md
rustler/src/serde/atoms.rs
rustler/src/serde/de.rs
rustler/src/serde/mod.rs
rustler/src/serde/ser.rs
rustler_tests/test/serde_rustler_tests_test.exs

This prevents ok/error atoms from getting mangled during transcoding. Also adds a sanity check so only Result variants get special treatment instead of any variant named "Ok" or "Err"

Serde: Restrict special ok/error handling to variant names

---

rustler/src/types/primitive.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/test_primitives.rs
rustler_tests/test/primitives_test.exs

Because of the weak difference in Elixir/Erlang between integers and floats (collectively "numbers"), it's common for a number that the BEAM stores internally as an integer to end up where a float was expected, usually with no consequences until we try to leave the erlang world and enter the very strongly typed Rust world.
This PR changes the decoder for f64 and f32 to transparently work on erlang terms that are internally integers. If decoding a term to f64 fails, it simply tries again as i64 and then casts it to the appropriate float type.
There's a lot of breaking up and reorganizing of macros in here too, both to cut down on boilerplate and to allow encoder/decoder impls to be generated separately (we only need to manually define float _decoders_, but the generic macros can still …

Allow floats to decode from integer terms

---

CHANGELOG.md
rustler/src/dynamic.rs
rustler_sys/build.rs

When adding the newer functions, I messed up the order and missed one function, which breaks rustler-sys for all newer API versions on Windows. Other OS are not affected by this, as they link the symbols directly instead of getting passed a struct.
Making the `rustler_sys` functions `extern "C"` just ensures that they look the same, independent of the operation system.

Fix Windows API functions

---

CHANGELOG.md
Cargo.toml
rustler/src/lib.rs
rustler/src/resource/arc.rs
rustler/src/resource/error.rs
rustler/src/resource/mod.rs
rustler/src/resource/registration.rs
rustler/src/resource/traits.rs
rustler_tests/lib/resource_dyncall.ex
rustler_tests/lib/rustler_test.ex
rustler_tests/native/resource_dyncall/Cargo.toml
rustler_tests/native/resource_dyncall/src/lib.rs
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_dyncall.rs
rustler_tests/test/resource_dyncall_test.exs
rustler_tests/test/test_helper.exs

This adds support for dynamic resource calls (https://www.erlang.org/doc/apps/erts/erl_nif#enif_dynamic_resource_call). The feature is inherently unsafe (exchanging pointers to mutable data between different dynamic libraries), though we might be able to eventually provide a stable API on top of it.
Changes to other parts:
- Exposes all of `rustler_sys` under `rustler::sys` s.t. it doesn't have to be explicitly referenced
- Adds helper function to compile tests and nif stubs only for particular NIF versions
- Ensures that `RustlerTest` can be loaded at startup

Add unsafe dyncall support

---

rustler/src/types/mod.rs

I encountered a Clippy warning that my enum got too big and I should box up my inner value, hence the PR ^^.

Implement Encoder and Decoder for Box<T>

---

CHANGELOG.md
rustler/src/codegen_runtime.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/lib.rs
rustler_tests/native/rustler_test/src/test_panic.rs
rustler_tests/test/panic_test.exs

Also adds tests for panicking in parameters, return values and the NIF
function itself.
Fixes #655

Catch panics in encoding NIF results

---

CHANGELOG.md
rustler/src/lib.rs
rustler/src/types/mod.rs
rustler/src/types/reference.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/test_env.rs
rustler_tests/test/env_test.exs

This is a first step towards #95.
`enif_make_ref` is the only direct `rustler_sys` reference I could find on github outside of `rustler` itself (in [extorch](https://github.com/andfoy/extorch/blob/6256c43689fa74904b0b60c9caae59bc8010c455/native/extorch/src/encoding/misc.rs#L3)). Since #653 is a potentially breaking change for direct users of `rustler_sys` (at least on Windows, where the initialisation won't get called anymore), this code needs to be adjusted on upgrade anyhow, so it makes sense to add the used functionality directly.

Add reference type and `make_ref` call

---

.github/workflows/main.yml
rustler_mix/lib/mix/tasks/rustler.new.ex
rustler_mix/lib/rustler.ex
rustler_mix/lib/rustler/compiler.ex
rustler_tests/test/serde_rustler_tests_test.exs

- **Run mix format --migrate to drop usage of 'unless'**
- **Flatten __before_compile__ macro to make the new type check happy** (fixes #669)
- **Add Elixir 1.18 release candidate to CI**

Elixir 1.18 tweaks and CI

---

CHANGELOG.md
rustler_codegen/src/ex_struct.rs
rustler_codegen/src/map.rs
rustler_tests/native/rustler_test/src/test_codegen.rs

This was probably a left-over from a refactoring. If the encoder was not requested, the macros compiled to code with a dangling `#[allow(...)]` which leads to a parser error.
Fixes #675.

Fix Nif* macros requiring an encoder

---

README.md

**problem**: GitHub Flavored Markdown (GFM) does not support Markdown's definition lists natively.
the current Readme file is rendering the definition list as:
`Type composition : Making a Rust struct encodable and decodable to Erlang or Elixir can be done : with a single attribute.`
**fix**: simulate a definition list using bold terms and line breaks

Replace unsupported definition list syntax in README.md

---

rustler/src/term.rs
rustler/src/types/atom.rs
rustler_tests/lib/rustler_test.ex
rustler_tests/native/rustler_test/src/test_map.rs

Alternative to #694. Fixes #693 and #474.
Uses the same has function for `Atom` and `Term`.
The other approach has the significant shortcoming that an atom has a different hash when represented as a `Term` and that it relies on the implementation detail that atom pointers are completely stable.
/edit: Previously also switched to phash2, but given how `std::hash::Hash` is used and documented (not even guaranteed to be stable across Rust versions), it doesn't really help us to pass more "portable" values in.

Implement Hash for atoms

---

.github/workflows/main.yml

- Add Elixir 1.19-rc and OTP28 to CI
- Drop OTP24 from CI
- Remove `brew` installation on macOS in favour of `setup-beam`'s new direct support (use `main` until there is a release)

CI Updates

---

rustler/Cargo.toml
rustler_codegen/src/init.rs

- Still lacks documentation
- The necessary mechanism was released with Erlang 28 (https://www.erlang.org/doc/apps/erts/erl_nif.html#initialization)
- Relevant discussion is https://github.com/rusterlium/rustler/discussions/687.
The general approach is to create a `staticlib` that depends on the relevant NIF libraries (all Rust-based ones have to be linked together) and then passing it into the `configure` script of OTP.

Static NIFs

---

rustler/src/env.rs
rustler/src/term.rs
rustler/src/types/binary.rs
rustler/src/types/list.rs
rustler/src/types/local_pid.rs
rustler/src/types/map.rs
rustler/src/types/primitive.rs
rustler/src/types/string.rs
rustler/src/wrapper/list.rs
rustler/src/wrapper/map.rs

I've gone through and added inline to some commonly used functions.
If everyone is happy, we could also add these to others.
We should judge **what** should be inlined. See https://nnethercote.github.io/perf-book/inlining.html
`None. The compiler will decide itself if the function should be inlined. This will depend on the optimization level, the size of the function, etc. If you are not using link-time optimization, functions will never be inlined across crates.`
`#[inline]. This suggests that the function should be inlined, including across crate boundaries.`
Amazingly I saw great wins with just this, as I have to call some of these functions a lot when encoding a lot of data.
This is using lto:
before
```
Operating System: macOS
CPU Information: Apple M1
Number of Available Cores: 8 …
```

Add inline tags to commonly used functions

---

rustler/src/codegen_runtime.rs
rustler/src/sys/types.rs
rustler_codegen/src/init.rs

Set `ErlNifEntry.min_erts` to a placeholder value
This value was introduced with NIF version 2.14 (so, OTP-21, erts-10.0).
Us leaving it unassigned and defaulting to NIF version 2.15 means the OTP is currently always putting a random pointer into the respective field here:
https://github.com/erlang/otp/blob/ae81b2f6ff2d541c01242f12cdbd5238aa4b26bd/erts/emulator/beam/erl_nif.c#L4581-L4585
It is used if one tries to load a NIF library that was compiled for a newer NIF version to display a debug message, at which point it would perform an out-of-bounds read.
As we currently default to NIF v2.15 (OTP-22) and only have features up to 2.16 (OTP-24), there are probably very few cases of this actually occurring in the wild.

Add required min_erts field
